export const projects = [
  {
    id: "tiny-app-baby-heartbeat-listener",
    title: "Tiny App: Baby Heartbeat Listener",
    description: "iOS app to listen to a baby’s heartbeat using Live Listen and real-time audio processing.",
    image: "/images/tiny-splashscreen.PNG",
    tags: ["iOS", "AudioKit", "Core Animation", "SwiftLint", "GitHub Actions"],
    githubUrl: "https://github.com/destucikal",
    appStoreUrl: "https://tinymiracle.life",
    details: "#### Audio Engineering & Visualization\nDeveloped a specialized iOS solution for real-time baby heartbeat monitoring, leveraging advanced audio processing frameworks.\n\n- **Real-time Visualization**: Implemented dynamic waveform rendering using Core Animation to provide visual feedback for audio signals.\n- **Audio Filtering**: Utilized AudioKit to refine raw audio input, specifically targeting frequencies relevant to fetal heartbeats while minimizing background noise.\n- **End-to-End Experience**: Designed and built the complete user journey, from onboarding to recording and playback flows.\n\n#### Engineering Rigor\n- **Code Quality**: Integrated SwiftLint to maintain a clean and consistent codebase.\n- **Automation**: Established CI/CD pipelines using GitHub Actions to automate linting and ensure project stability.",
    videoUrl: "/images/tiny-demo.mp4",
  },
  {
    id: "telly-bisindo-sign-language-learning",
    title: "Telly: BISINDO Sign Language Learning",
    description: "Indonesian Sign Language learning app using Create ML and interactive course progression.",
    image: "/images/telly-splashscreen.PNG",
    tags: ["iOS", "SwiftUI", "Create ML", "SwiftData"],
    githubUrl: "https://github.com/destucikal",
    appStoreUrl: "",
    details: "#### Interactive Learning System\nBuilt a modern educational platform for Indonesian Sign Language (BISINDO), focusing on interactive engagement and progress tracking.\n\n- **ML-Powered Learning**: Integrated Create ML models to facilitate real-time sign recognition and interactive learning feedback.\n- **Gamified Progression**: Developed a structured course selection system with dynamic lock/unlock logic based on user performance and completion.\n- **Fluid UI/UX**: Crafted animated interface elements using SwiftUI's `withAnimation` modifier, ensuring a polished and responsive learning environment.\n\n#### Data Persistence\n- **Progress Tracking**: Leveraged SwiftData for lightweight, local storage of user course states and achievement history.",
    videoUrl: "/images/telly-demo.mov",
  },
  {
    id: "solari-running-companion",
    title: "Solari: Running Tracker",
    description: "Running tracker app using SwiftUI, MapKit, and Core Location for real-time metrics and route visualization.",
    image: "/images/solari-runhome.PNG",
    tags: ["iOS", "SwiftUI", "MapKit", "Core Location", "SwiftData"],
    githubUrl: "https://github.com/destucikal",
    appStoreUrl: "",
    details: "#### Tracking & Spatial Data\nDeveloped a comprehensive running tracker that prioritizes accuracy and real-time user feedback.\n\n- **Precise Metrics**: Implemented Core Location to accurately calculate pace, distance, and duration during active sessions.\n- **Route Visualization**: Integrated MapKit to render real-time breadcrumb paths, allowing users to visualize their running routes as they happen.\n- **Metric Summaries**: Built intentional result screens that summarize run statistics through a clear, data-focused UI.\n\n#### Session Management\n- **Local Persistence**: Integrated SwiftData to manage and persist historical running sessions, allowing for offline access and performance trends.",
    videoUrl: "",
  },
  {
    id: "snorkeling-booking-app",
    title: "Snorkeling Booking App",
    description: "Led cross-functional teams to improve the post-purchase experience for a consumer snorkeling app.",
    image: "https://images.unsplash.com/photo-1544551763-46a013bb70d5?auto=format&fit=crop&q=80&w=1000",
    tags: ["Product Management", "UX Research", "Metric Definition"],
    githubUrl: "https://github.com/destucikal",
    appStoreUrl: "",
    details: "#### Product Strategy & Leadership\nLed a cross-functional squad to redefine the post-purchase experience, focusing on user retention and satisfaction.\n\n- **Cross-Functional Leadership**: Managed a team of 7 stakeholders across design, engineering, and operations to deliver an initial end-to-end solution.\n- **Decision Frameworks**: Employed effort-impact matrices to evaluate potential solutions and prioritize features for the MVP.\n- **Concept Validation**: Conducted structured user interviews to test concepts and gather qualitative feedback before full implementation.\n\n#### Requirements Engineering\n- **Definition & QA**: Authored comprehensive epics, user stories, and test cases covering both positive and edge-case negative flows to ensure product quality.",
    videoUrl: "",
  },
  {
    id: "p2p-lending-app-fraud-prevention",
    title: "P2P Lending App: Fraud Prevention",
    description: "Developed document liveness detection using machine learning to prevent user fraud.",
    image: "https://images.unsplash.com/photo-1563986768609-322da13575f3?auto=format&fit=crop&q=80&w=1000",
    tags: ["Machine Learning", "Image Classification", "Computer Vision"],
    githubUrl: "https://github.com/destucikal",
    appStoreUrl: "",
    details: "#### Computer Vision & Security\nEngineered a document liveness detection system to mitigate fraud within a P2P lending platform.\n\n- **Model Development**: Built a multiclass image classification model designed to distinguish between authentic KTP documents and fraudulent reproductions.\n- **Dataset Engineering**: Prepared, curated, and augmented datasets to improve model robustness across various lighting and orientation conditions.\n- **Evaluation & Training**: Utilized Google Colab for model training and iterative evaluation of accuracy and precision metrics.\n\n#### Taxonomy Design\n- **Class Definition**: Defined a rigorous class taxonomy for liveness detection to handle nuanced fraud patterns.",
    videoUrl: "",
  },
]

export const blogPosts = [
  {
    slug: "mastering-swiftui-layouts",
    title: "Mastering SwiftUI Layouts: ZStack, VStack, and HStack",
    excerpt: "A deep dive into the layout system of SwiftUI and how to build complex interfaces with simple stacks.",
    date: "2024-03-15",
    content: "SwiftUI layouts are declarative and powerful. By combining ZStack, VStack, and HStack, you can create complex and responsive user interfaces with minimal code.\n\nIn this tutorial, we will explore:\n- How to use VStack for vertical alignment.\n- How to use HStack for horizontal alignment.\n- How to use ZStack for layering views on top of each other.\n- Best practices for nesting stacks to create sophisticated layouts.",
    tags: ["SwiftUI", "Tutorial"],
  },
  {
    slug: "getting-started-with-ios-development",
    title: "Getting Started with iOS Development in 2025",
    excerpt: "The landscape of iOS development is evolving. Here's what you need to focus on this year.",
    date: "2025-12-25",
    content: "The landscape of iOS development is evolving. Here's what you need to focus on this year.\n\nWith the release of new hardware and software features, Swift and SwiftUI continue to lead the way in mobile app development. Focus on mastering Swift 6 concurrency, the latest SwiftUI APIs, and integrating AI-driven features to stay ahead of the curve.",
    tags: ["Career", "Swift", "iOS"],
  },
]
